server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AslamSujah/spring-cloud-config-store.git
          # username: git username  It requires when we use private repository
          # password: git password  It requires when we use private repository
